#!/bin/sh
# Test the sweet translators by doing a round-trip.
# Tests using the filename in $1, or a default filename if none given.

# TODO: ./sweet-filter doesn't copy out a comment if it was immediately
# preceded by a line with a datum.  Need to fix.

# For the given test file (which must be in traditional S-expression format),
# 1. Pretty-print it (placing it in ,1)
# 2. Convert to sweet, then convert back to S-expressions (placing it in ,2)
# They should be the same.  This puts stress on both converters.

TESTFILE="${1:-sweeten.scm}"

make sweeten.scm

if [ ! -f "$TESTFILE" ]
then
  echo "Failure: File $TESTFILE does not exist."
  exit 1
fi

./pprint < "$TESTFILE" > ,1

./sweeten   < "$TESTFILE" > ,2.sweet
./unsweeten < ,2.sweet | ./pprint > ,2

echo "DIFFERENCES (should be none):"
echo
diff -u ,1 ,2
