#!/bin/sh
# sweet-clisp [FILE [args]]

# By David A. Wheeler. Start up clisp in "sweet-expression" reading mode,
# so you can try it out.  Setting *print-escape* isn't ideal, but
# in most circumstances it works well, and clisp has no better way
# of disabling unnecessary escapes.

# If you want to use local un-installed file, cd to dir with .slisp files and:
#    CL_SOURCE_REGISTRY="$PWD" ./sweet-clisp ...
# you can also replace "$PWD" with the readable .lisp files' directory.

clisp_options="-modern"

setup_commands='
(require "asdf")
(asdf:load-system :readable)
(setq *print-escape* nil)
(readable:enable-sweet)
'

if [ $# -gt 0 ] ; then

  origfile="$1"
  shift

  commandfile="$(mktemp)"
  printf "$setup_commands" > "$commandfile"
  cat -- "$origfile" >> "$commandfile"

  clisp --quiet --quiet $clisp_options "$commandfile" "$@"

  # Clean up.
  rm -fr "$commandfile"

else

  clisp $clisp_options -x "$setup_commands" -repl

fi

