#!/bin/sh

# By David A. Wheeler. Start up clisp in "sweet-expression" reading mode,
# so you can try it out.

(
cat << COMMAND_SET
(load "tests/my-asdf.lisp")
(asdf:load-system :readable)
(readable:enable-sweet)
COMMAND_SET

if which stdbuf 2> /dev/null ; then
  STDBUF=stdbuf -oL
else
  STDBUF=""
fi

$STDBUF cat "$@"
printf "\n\n"  # Ensure it ends on newlines.
) | \
 CL_SOURCE_REGISTRY="$PWD" "/usr/bin/clisp" -lp "$PWD" -modern

