#!/bin/sh
# Filter to read S-expressions and output indented sweet-expressions.

# Requires guile and runs sweeten.sscm.
# Currently presumes sweeten.sscm is in the same path as
# this file.

exec env -i HOME=$HOME GUILE_LOAD_PATH="`dirname $0`" guile -q -s $0
!#

(use-modules (readable sweet-impl))
(replace-read sweet-read)
(load "sweeten.sscm")
