#!/bin/sh

# Run an arbitrary program expressed using sweet-expressions.
# First parameter is the filename of a script to run through
# Sweet-expression parser, then run the result.
# The arbitrary program will probably look like this:
#   #!sweet-run
#   ;#!guile -s
#   ;!#
# Where "guile -s" might be scsh or something else.

result="$(mktemp)"

UNSWEETEN="./unsweeten"

tail -n +2 < "$1" | "${UNSWEETEN}" > "$result"
chmod u+x "$result"

shift

# Create full name, so we can be sure we can execute it no matter what
# mktemp's settings are.
fullname="$(dirname "$result")/$(basename "$result")"

# Run it, passing all the parameters we got.
"$fullname" "$@"

# Erase temp file # once we're done with it:
rm -f -- "$result"
