#!/bin/sh
# Start up sbcl in "sweet-expression" mode.
# sweet-sbcl [sbcl-options]

# To run an UNINSTALLED readable library, do this:
#    CL_SOURCE_REGISTRY="$PWD" ./sweet-sbcl
# You can run scripts, e.g.:
#    CL_SOURCE_REGISTRY="$PWD" ./sweet-sbcl --script FILE.slisp

sbcl --eval '(require "asdf")' \
     --eval '(asdf:load-system :readable)' \
     --eval '(readable:enable-sweet)' "$@"

