#!/bin/sh

antlrworks_jar=../antlrworks-1.4.3.jar
output_dir=.
# Note: Remove GNU extension --strip-trailing-cr if you don't have it
diff_options="-u --strip-trailing-cr"

if [ -x /usr/bin/cygpath ] ; then
  antlrworks_jar="$(cygpath -wa $antlrworks_jar)"
  output_dir="$(cygpath -wa $output_dir)"
fi

CLASSPATH="$CLASSPATH;$antlrworks_jar;$output_dir"
echo "CLASSPATH=\"$CLASSPATH\""
echo

# Clear out old version
rm -f output.txt

echo "About to compile"
javac scheme/*.java [A-Z]*.java &&
  echo "Compilation complete, now running tests." &&
  java Unsweeten_ANTLR < input.txt | tee output.txt

echo
echo "Differences from correct:"
if diff $diff_options correct.txt output.txt
then
 echo
 echo "ALL TESTS PASS!"
else
 echo
 echo "Differences found.  If this is correct, run:"
 echo "  cp output.txt correct.txt"
fi
