#!/bin/sh
# Test the sweet translators by doing a round-trip.
# Tests using the filename in $1, or a default filename if none given.

# TODO: ./unsweeten doesn't copy out a comment if it was immediately
# preceded by a line with a datum.  Need to fix.

# For the given test file (which must be in traditional S-expression format),
# 1. Pretty-print it (placing it in ,1)
# 2. Convert to sweet, then convert back to S-expressions (placing it in ,2)
# They should be the same.  This puts stress on both converters.

TESTFILE="${1:-sweeten.scm}"

# make sweeten.scm

if [ ! -f "$TESTFILE" ]
then
  echo "Failure: File $TESTFILE does not exist."
  exit 1
fi

pprint < "$TESTFILE" > ,1

sweeten   < "$TESTFILE" > ,2.sscm
unsweeten < ,2.sscm | pprint > ,2

echo "Roundtrip differences (should be none):"
echo
if diff -u ,1 ,2 ; then
  echo "No differences, all well!"
  rm -f ,1 ,2 ,2.sscm
  exit 0
else
  echo "DIFFERENCES.  See ,1 and ,2.sscm and ,2 for more details"
  exit 1
fi
