#!/bin/sh

# diff-s-sweet: Given two filenames
# (in s-expressions and sweet-expressions respectively),
# show the semantic differences between them.
# If there's a difference, show the difference and return an error code,
# else show nothing and return true (0).

# (C) 2013 David A. Wheeler
# Released under the MIT license

export PATH="@PATH_PREFIX@$PATH"
SWEETEN="sweeten"
UNSWEETEN="unsweeten"

if [ $# -ne 2 ] ; then
  echo "Usage: $0 s-expression-filename sweet-expression-filename"
  exit 99
fi
if [ ! -f "$1" ] ; then
  echo "File 1 (for s-expressions) must exist as a normal file"
  exit 98
fi
if [ ! -f "$2" ] ; then
  echo "File 2 (for sweet-expressions) must exist as a normal file"
  exit 98
fi

# The sed commands deletes ;-only lines; the awk command
# merges 2+ blank lines into one blank line.
# We don't ignore ALL blank lines, because blank lines can have an effect.
# For example, a blank line followed by an indent has
# a different meaning if we remove the blank line.
# All of this assumes that we're not using multi-line strings.

${SWEETEN} "$1" | ${UNSWEETEN} | \
  sed -e '/[ 	]*;/d' | \
  awk '/^$/{ if (! blank++) print; next } { blank=0; print }' > ,first

${UNSWEETEN} "$2" | \
  sed -e '/[ 	]*;/d' | \
  awk '/^$/{ if (! blank++) print; next } { blank=0; print }' > ,second

diff -u ,first ,second
